modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"

[[mods]]
modId = "flight_on_elytras"
version = "${version}"
displayName = "VisorFlightOnElytras"
authors = "Ninix"
displayTest = "NONE"
description = '''
Flight On Elytras Addon for Visor

'''

[[dependencies.flight_on_elytras]]
modId = "visor"
mandatory = true
versionRange = "[0.2.0-alpha,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.flight_on_elytras]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.flight_on_elytras]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "AFTER"
side = "BOTH"
